import http from "./httpServices";

// const episodes = [
// 	{
// 		id: 1,
// 		poster: "/assets/images/anime6.jpg",
// 		episodeTitle: "The Start of the begining",
// 		episodeNo: 1,
// 		showName: "Re:Zero kara Hajimeru Isekai Seikatsu",
// 		showId: 1,
// 		category: "anime",
// 		authorId: 1,
// 		author: "mustafa_salah",
// 		comments: 4,
// 		status: "published",
// 		publishDate: "2019-07-12",
// 		views: 234,
// 	},
// 	{
// 		id: 2,
// 		poster: "/assets/images/anime6.jpg",
// 		episodeTitle: "Reunion with the Witch",
// 		episodeNo: 2,
// 		showName: "Re:Zero kara Hajimeru Isekai Seikatsu",
// 		showId: 1,
// 		category: "anime",
// 		authorId: 1,
// 		author: "mustafa_salah",
// 		comments: 22,
// 		status: "published",
// 		publishDate: "2019-07-17",
// 		views: 758,
// 	},
// 	{
// 		id: 3,
// 		poster: "/assets/images/anime2.jpg",
// 		episodeTitle: "A Ruler's Melancholy",
// 		episodeNo: 1,
// 		showName: "Overlord",
// 		showId: 2,
// 		category: "anime",
// 		authorId: 1,
// 		author: "mustafa_salah",
// 		comments: 11,
// 		status: "published",
// 		publishDate: "2019-07-23",
// 		views: 323,
// 	},
// 	{
// 		id: 4,
// 		poster: "/assets/images/hxh.jpg",
// 		episodeTitle: "Friend X Trip",
// 		episodeNo: 94,
// 		showName: "Hunter X Hunter",
// 		showId: 3,
// 		category: "anime",
// 		authorId: 2,
// 		author: "aliosman",
// 		comments: 11,
// 		status: "published",
// 		publishDate: "2019-08-03",
// 		views: 3456,
// 	},
// 	{
// 		id: 5,
// 		poster: "/assets/images/anime3.jpg",
// 		episodeTitle: "Hard Death",
// 		episodeNo: 1,
// 		showName: "Death Parade",
// 		showId: 4,
// 		category: "anime",
// 		authorId: 1,
// 		author: "mustafa_salah",
// 		comments: 3,
// 		status: "published",
// 		publishDate: "2019-08-08",
// 		views: 847,
// 	},
// 	{
// 		id: 6,
// 		poster: "/assets/images/anime4.jpg",
// 		episodeTitle: "Mutual fraud",
// 		episodeNo: 2,
// 		showName: "Juuni Taisen",
// 		showId: 5,
// 		category: "anime",
// 		authorId: 3,
// 		author: "mohamed_mosa",
// 		comments: 3,
// 		status: "published",
// 		publishDate: "2019-08-12",
// 		views: 543,
// 	},
// ];

export default async function getEpisodes(id) {
	const episodes = await http.get(`/episodes/${id || ""}`);
	return episodes.data;
}
